app = "community-chess"
primary_region = "sea"

[build]
dockerfile = "Dockerfile"

[mounts]
source = "community_chess_db" # name
destination = "/sqlite" # mount point matches Dockerfile
initial_size = "1GB"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256 # For free tier
