# To deploy without redundancy: 
# fly deploy --ha=false
# fly scale count 1 # For existing deployments

app = "community-chess"
primary_region = "sea"

[build]
dockerfile = "Dockerfile"

# View the volume in the Machine file system:
# fly ssh console -s -C df
[mounts]
source = "community_chess_db" # name
destination = "/sqlite" # mount point matches Dockerfile
initial_size = "1GB"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256 # For free tier
